### ISSUE TITLE
用这个折腾了那个laravel-excel，各种报错，放弃了，建议谨慎使用

### ISSUE THREAD

**Issue by Mr-ShiHuaYu** [mouyong/webman-laravel#3]
Error: Call to undefined method support\Response::deleteFileAfterSend() in D:\4.PHP\Code\webman_laravel_test\vendor\maatwebsite\excel\src\Excel.php:87
Stack trace:
#0 D:\4.PHP\Code\webman_laravel_test\vendor\illuminate\support\Facades\Facade.php(338): Maatwebsite\Excel\Excel->download(Object(app\Exports\UsersExport), 'users.xlsx')
#1 D:\4.PHP\Code\webman_laravel_test\app\controller\IndexController.php(29): Illuminate\Support\Facades\Facade::__callStatic('download', Array)
#2 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\webman-framework\src\App.php(325): app\controller\IndexController->export(Object(support\Request))
#3 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\webman-framework\src\App.php(141): Webman\App::Webman\{closure}(Object(support\Request))
#4 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\workerman\Connection\TcpConnection.php(646): Webman\App->onMessage(Object(Workerman\Connection\TcpConnection), Object(support\Request))
#5 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\workerman\Events\Select.php(311): Workerman\Connection\TcpConnection->baseRead(Resource id #554)
#6 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\workerman\Worker.php(1485): Workerman\Events\Select->loop()
#7 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\workerman\Worker.php(1402): Workerman\Worker::forkWorkersForWindows()
#8 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\workerman\Worker.php(560): Workerman\Worker::forkWorkers()
#9 D:\4.PHP\Code\webman_laravel_test\vendor\workerman\webman-framework\src\support\App.php(131): Workerman\Worker::runAll()
#10 D:\4.PHP\Code\webman_laravel_test\start.php(8): support\App::run()
#11 {main}

**Comment by mouyong** [comment]
有部分我没去验证。在 webman 里面同时兼容 laravel 的生态。有很大的难度。我后来也放弃这样做了
